### ISSUE TITLE
Clicking on a mention of a new account crashes the app

### ISSUE THREAD

**Issue by issimonwoods** [microdotblog/microblog-mac#20]
I included a mention to a new account [in my post](https://micro.blog/SimonWoods/19424883) (`@check`) and then clicked on it afterwards. The app crashes when I do so.

**Comment by manton** [comment]
"check" was supposed to be a reserved name in the API, so it's causing some problems. Which app is crashing?

**Comment by manton** [comment]
Sorry, just realized this is in the Mac repo. Thanks!
