### ISSUE TITLE
Minor UI bug: "Publishing" text wraps at the default window size

### ISSUE THREAD

**Issue by ryanbooker** [microdotblog/microblog-mac#27]
<img width="570" alt="Screenshot 2023-11-25 at 07 55 59" src="https://github.com/microdotblog/microblog-mac/assets/7423/23bb59a7-caa1-4ffb-9d54-14743e772449">

**Comment by manton** [comment]
Thanks. I can't reproduce this but I think it's because it depends on the length of the username. Will work on fixing it.

**Comment by danielpunkass** [comment]
I was able to reproduce it with my longer username :) ... mine distorted in an even less readable way.

<img width="682" alt="Screenshot 2023-11-29 at 4 20 35 PM" src="https://github.com/microdotblog/microblog-mac/assets/14606/70f56276-a491-454e-8a3d-966dbb95975a">

**Comment by danielpunkass** [comment]
I will take a quick look and see if I can reproduce from source and if it's an easy fix I'll submit  PR.

**Comment by danielpunkass** [comment]
I came up with a pragmatic fix that addresses the issue by:

1. Changing the Text Field line break mode to truncate instead of line wrap.
2. Increasing the minimum width of the status bubble so that it's big enough to hold "Publishing…"

Will send a PR soon.

**Comment by danielpunkass** [comment]
Video demonstrating the new behavior:

https://github.com/microdotblog/microblog-mac/assets/14606/ea9028b8-8c11-4ce2-b6ca-5df9caedb0b4

**Comment by manton** [comment]
Looks much better. 👍
