### ISSUE TITLE
macOS app isn’t uploading GIFs 

### ISSUE THREAD

**Issue by uncertainquark** [microdotblog/microblog-mac#8]
I tried to publish [this post](https://micro.jatan.space/2021/07/22/years-ago-today.html) via the macOS app and it uploaded the GIF as an jpg to both micro.blog as well as all the crossposted platforms. I had to go and delete all the posts one by one. Then I tried posting the GIF from micro.blog’s website and everything worked fine.

Not sure if iOS has the problem too.

**Comment by manton** [comment]
This is fixed in the upcoming Mac 2.1.1 release.
